/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.BorderLayout;
import java.awt.Dimension;

/**
 *
 * @author yoshi
 */
public class SubmodulosAdmin extends javax.swing.JPanel {

    /**
     * Creates new form SubmodulosAdmin
     */
    public SubmodulosAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTrabajadores = new javax.swing.JButton();
        btnReporteEntrada = new javax.swing.JButton();
        btnReporteSalida = new javax.swing.JButton();
        btnHistorialCambios = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(230, 330));
        setMinimumSize(new java.awt.Dimension(230, 330));
        setPreferredSize(new java.awt.Dimension(230, 330));

        btnTrabajadores.setFont(new java.awt.Font("SF UI Display", 0, 16)); // NOI18N
        btnTrabajadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconTrabajador.png"))); // NOI18N
        btnTrabajadores.setText("Trabajadores");
        btnTrabajadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrabajadores.setMaximumSize(new java.awt.Dimension(230, 50));
        btnTrabajadores.setMinimumSize(new java.awt.Dimension(230, 50));
        btnTrabajadores.setPreferredSize(new java.awt.Dimension(230, 50));
        btnTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrabajadoresActionPerformed(evt);
            }
        });

        btnReporteEntrada.setFont(new java.awt.Font("SF UI Display", 0, 16)); // NOI18N
        btnReporteEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/entrada.png"))); // NOI18N
        btnReporteEntrada.setText("Reporte Entradas");
        btnReporteEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporteEntrada.setMaximumSize(new java.awt.Dimension(230, 50));
        btnReporteEntrada.setMinimumSize(new java.awt.Dimension(230, 50));
        btnReporteEntrada.setPreferredSize(new java.awt.Dimension(230, 50));
        btnReporteEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteEntradaActionPerformed(evt);
            }
        });

        btnReporteSalida.setFont(new java.awt.Font("SF UI Display", 0, 16)); // NOI18N
        btnReporteSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/salida.png"))); // NOI18N
        btnReporteSalida.setText("Reporte Salidas");
        btnReporteSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporteSalida.setMaximumSize(new java.awt.Dimension(230, 50));
        btnReporteSalida.setMinimumSize(new java.awt.Dimension(230, 50));
        btnReporteSalida.setPreferredSize(new java.awt.Dimension(230, 50));
        btnReporteSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteSalidaActionPerformed(evt);
            }
        });

        btnHistorialCambios.setFont(new java.awt.Font("SF UI Display", 0, 16)); // NOI18N
        btnHistorialCambios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconCambio.png"))); // NOI18N
        btnHistorialCambios.setText("Historial de Cambios");
        btnHistorialCambios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorialCambios.setMaximumSize(new java.awt.Dimension(230, 50));
        btnHistorialCambios.setMinimumSize(new java.awt.Dimension(230, 50));
        btnHistorialCambios.setPreferredSize(new java.awt.Dimension(230, 50));
        btnHistorialCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReporteEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReporteSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistorialCambios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnReporteEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnReporteSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnHistorialCambios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrabajadoresActionPerformed
        SubmoduloTrabajador mTraba = new SubmoduloTrabajador();
        
        mTraba.setSize(new Dimension(970, 550));
        mTraba.setLocation(0,0);
        Principal.PanelPrincipal.removeAll();
        Principal.PanelPrincipal.add(mTraba,BorderLayout.CENTER);
        Principal.PanelPrincipal.revalidate();
        Principal.PanelPrincipal.repaint();
    }//GEN-LAST:event_btnTrabajadoresActionPerformed

    private void btnReporteEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteEntradaActionPerformed
        SubmoduloReporteEntradas mEntrada = new SubmoduloReporteEntradas();
        
        mEntrada.setSize(new Dimension(970, 550));
        mEntrada.setLocation(0,0);
        Principal.PanelPrincipal.removeAll();
        Principal.PanelPrincipal.add(mEntrada,BorderLayout.CENTER);
        Principal.PanelPrincipal.revalidate();
        Principal.PanelPrincipal.repaint();
    }//GEN-LAST:event_btnReporteEntradaActionPerformed

    private void btnReporteSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteSalidaActionPerformed
        SubmoduloReporteSalidas mSalida = new SubmoduloReporteSalidas();
        
        mSalida.setSize(new Dimension(970, 550));
        mSalida.setLocation(0,0);
        Principal.PanelPrincipal.removeAll();
        Principal.PanelPrincipal.add(mSalida,BorderLayout.CENTER);
        Principal.PanelPrincipal.revalidate();
        Principal.PanelPrincipal.repaint();
    }//GEN-LAST:event_btnReporteSalidaActionPerformed

    private void btnHistorialCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialCambiosActionPerformed
        SubmoduloReporteCambios mCambios = new SubmoduloReporteCambios();
        
        mCambios.setSize(new Dimension(970, 550));
        mCambios.setLocation(0,0);
        Principal.PanelPrincipal.removeAll();
        Principal.PanelPrincipal.add(mCambios,BorderLayout.CENTER);
        Principal.PanelPrincipal.revalidate();
        Principal.PanelPrincipal.repaint();
    }//GEN-LAST:event_btnHistorialCambiosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistorialCambios;
    private javax.swing.JButton btnReporteEntrada;
    private javax.swing.JButton btnReporteSalida;
    private javax.swing.JButton btnTrabajadores;
    // End of variables declaration//GEN-END:variables
}
